### ISSUE TITLE
run apache behind a reverse-proxy (HAproxy)

### ISSUE THREAD

**Issue by pierreozoux** [fkooman/php-remote-storage#36]
So, I'm almost done dockerizing it :)

I run apache on port 80, and then I ssl to HAproxy that is running on 443.
Here is the way I start the apache: https://github.com/indiehosters/remoteStorage

it works until I try to login (foo:bar).
You can try it here: https://rs.indie.host/

You get a:
```
Bad Request

HTTP_REFERER has unexpected value
```

I tried to set the right headers from apache (and even to set the referer):
https://github.com/indiehosters/remoteStorage/commit/13cecce02aaf42d59e96c7f2f1be6a468b09a98c

But still the same issue.

How can I set up some more debug to help us tackle that issue?

**Comment by fkooman** [comment]
The referer is something that the browser sets, it is needed to avoid CSRF. So it is important that the forwarding proxy does NOT set it. For testing it was fine, but I think we're getting close to the problem now:

Try adding 

    ServerName rs.indie.host

To your apache vhost config, that should solve it :) The request URI is determined based on SERVER_NAME variable and not the Host of the HTTP request.

**Comment by fkooman** [comment]
By the way, I also have a PHP FPM Apache configuration file here: https://github.com/fkooman/php-remote-storage-deployment/blob/master/storage.example-httpd.conf

**Comment by pierreozoux** [comment]
Still no luck... I don't think php fpm will change any thing.
There is something funny, but I can't put the finger on it...

I make apache log the http_referer and it is: `https://rs.indie.host/_account`

Do you want me to log anything else to try to debug?

**Comment by fkooman** [comment]
```
diff --git a/web/index.php b/web/index.php
index d06ebba..20994d5 100644
--- a/web/index.php
+++ b/web/index.php
@@ -39,6 +39,8 @@ use fkooman\Tpl\Twig\TwigTemplateManager;
 try {
     $request = new Request($_SERVER);
 
+    error_log($request->getUrl()->toString());
+
     $configReader = new Reader(
         new YamlFile(
             dirname(__DIR__).'/config/server.yaml'
```

This should print the request URL in the error log... That should give us a clue :)

**Comment by fkooman** [comment]
It has something to do with this: https://en.wikipedia.org/wiki/X-Forwarded-For.

Can you also log the `X-Forwarded-For` header? I guess it is set by HA proxy? If that is set by default I will modify the code to work with that out of the box!

**Comment by fkooman** [comment]
Hmm... I just have a bug in my code it seems :) It is actually a FIXME.

```
        // FIXME: we should also inspect the target port in case of HTTP
        // proxy to see if we need to specify a (different) port
```

**Comment by fkooman** [comment]
I have a fix now, I just hope no one gets the idea to run a HTTPS proxy on a different port than 443 :)

**Comment by fkooman** [comment]
I uploaded 0.9.9 that contains the fix! Let me know if that works :)

**Comment by pierreozoux** [comment]
Yis! It worked \o/ Thanks a lot!

**Comment by fkooman** [comment]
Yeah!

Would it be a lot of work to use php-fpm instead? It is a big improvement for performance!

**Comment by fkooman** [comment]
It seems it is much easier to use HTTP_HOST header, then you always know if from the point of view of the client a different port is used. I'm implementing that now in `fkooman/http`. Hope that it won't break your setup, although I do have a unit test for your specific case that is tested and still works...
